trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  # shared-variables group should contain:
  # AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP
  - group: shared-variables
  - name: AZML_DATAPATH
    value: titanic-data

steps:
# - task: AzureCLI@1
#   displayName: Login to Azure CLI
#   inputs:
#     azureSubscription: 'Microsoft (AIRS) (52512f28-c6ed-403e-9569-82a9fb9fec91)'
#     scriptLocation: inlineScript
#     inlineScript: 'az account list'

- task: UsePythonVersion@0
  displayName: Use Python 3.6
  inputs:
    versionSpec: '3.6'
    addToPath: true 

#pip3 install setuptools
- bash: |
    pip3 install -r requirements.txt
  workingDirectory: aml
  displayName: Install pip package requirements
    
# - task: PythonScript@0
#   displayName: Start AML data prep script
#   inputs:
#     scriptSource: filePath
#     scriptPath: aml/titanic/prep-data.py
#     workingDirectory: aml/titanic

- task: AzureCLI@1
  displayName: Start AML data prep script
  inputs:
    azureSubscription: 'Microsoft (AIRS) (52512f28-c6ed-403e-9569-82a9fb9fec91)'
    scriptLocation: inlineScript
    inlineScript: python3 prep-data.py
    workingDirectory: aml/titanic