trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets

steps:
- task: AzureCLI@1
  displayName: 'Login to Azure CLI'
  inputs:
    azureSubscription: 'Microsoft (AIRS) (52512f28-c6ed-403e-9569-82a9fb9fec91)'
    scriptLocation: inlineScript
    inlineScript: 'az account list'

# - bash: |
#     pip3 install setuptools
#     pip3 install -r requirements.txt
#   workingDirectory: aml

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true 
    
- task: PythonScript@0
  inputs:
    scriptSource: filePath
    scriptPath: aml/titanic/prep-data.py
    #workingDirectory: aml/titanic