trigger: none

queue:
  name: Hosted Ubuntu 1604

steps:
- task: AzureCLI@1
  displayName: 'Login to Azure CLI'
  inputs:
    azureSubscription: 'Microsoft (AIRS) (52512f28-c6ed-403e-9569-82a9fb9fec91)'
    scriptLocation: inlineScript
    inlineScript: 'az account list'

- bash: |
    pip3 install -r requirements.txt
  workingDirectory: aml

- bash: |
    python3 prep-data.py
  workingDirectory: aml/titanic
