title: "Project Batcomputer"
remote_theme: benc-uk/theme-msdark
favicon: /batclient/favicon.png
plugins:
  - jemoji
header-colours: 
  right: "#1E3AB3"
  left: "#2bcfa8"
buttons:
  - b0:
    text: Slides
    href: /docs/Project-Bat-Computer-Slides.pdf