title: "Project Batcomputer"
remote_theme: benc-uk/theme-msdark
favicon: /batclient/favicon.png
plugins:
  - jemoji
header-colours: 
  right: "#077fb7"
  left: "#0f1b26"
buttons:
  - bmain:
    text: Main Page
    href: /
  - bslides:
    text: Slides
    href: /docs/Project-Bat-Computer-Slides.pdf