apiVersion: v1
appVersion: "alpha"
description: A Helm chart to deploy Batcomputer microservices API app to Kubernetes
name: batcomputer
version: 1.0.0
icon: https://github.com/benc-uk/smilr/raw/master/angular/src/assets/img/logo.png
maintainers: 
  - name: Ben Coleman
    email: ben.coleman@microsoft.com
# home: https://github.com/benc-uk/smilr
# sources:
#   - https://github.com/benc-uk/smilr