#
# Azure Pipeline for building the base python-scikit image
# Ben C, 2019
#

trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: scikit-version
    value: "0.18.1"
  - name: dockerhub-user
    value: bencuk

steps:
- script: |
    docker build . -f scikit.Dockerfile --build-arg SCIKIT_VERSION=$(scikit-ver) --build-arg PYTHON_VERSION=3.5.6 -t $(dockerhub-user)/python-scikit:$(scikit-ver)
  displayName: 'Build base python-scikit image'

- script: |
    docker login -u $(dockerhub-user) -p $(dockerhub-password)
    docker push $(dockerhub-user)/python-scikit:$(scikit-ver)
  displayName: 'Push python-scikit image up to Dockerhub'

