trigger:
  branches:
    include:
    - master
  paths:
    include:
    - training/scikit-titanic.py
    - aml/run-training.py

queue:
  name: Hosted Ubuntu 1604

variables:
  # shared-variables group MUST contain: AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP, AZML_COMPUTE_NAME
  - group: shared-variables

  - name: SCRIPT_NAME
    value: run-training.py

  - name: AZML_DATAPATH
    value: titanic-data

  - name: AZML_MODEL
    value: titanic-model

  - name: AZML_EXPERIMENT
    value: titanic

steps:
- template: templates/run-aml-python.yml