trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  # shared-variables group MUST contain: AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP
  - group: shared-variables

  - name: azure-connection-name
    value: Microsoft (AIRS) (52512f28-c6ed-403e-9569-82a9fb9fec91)

  - name: script-name
    value: upload-data.py

  - name: script-args
    value: ../data/titanic

  - name: AZML_DATAPATH
    value: titanic-data
    
steps:
- template: templates/run-aml-python.yml