trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: model-name
    value: batcomputer
  - name: notebook-name
    value: scikit-batcomputer    
  - name: job-id
    value: "4"
  - name: job-params
    value: '{ "model_version":"$(version)", "model_name":"$(model-name)", "storage_account":"$(storage-account)" }'

steps:
- template: templates/run-databricks-job.yaml