trigger:
  branches:
    include:
    - master
  paths:
    include:
    - notebooks/*

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: model-name
    value: titanic
  - name: notebook-name
    value: scikit-titanic
  - name: job-id
    value: "1"
  - name: job-params
    value: '{ "model_version":"$(version)", "model_name":"$(model-name)", "storage_account":"$(storage-account)" }'
    
steps:
- template: templates/run-databricks-job.yaml