trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: model-name
    value: titanic
  - name: job-id
    value: "1"

steps:
- template: templates/run-databricks-job.yaml