trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  - name: databricks-host
    value: https://westeurope.azuredatabricks.net
  - name: job-id
    value: "1"
  - name: job-params
    value: '{ \"model_version\": \"$(version)\"}'

steps:
- template: templates/run-databricks-job.yaml