trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: model-name
    value: batcomputer
  - name: job-id
    value: "2"

steps:
- template: templates/run-databricks-job.yaml